version: '3.8'

services:
  backend:
    container_name: To-DO_app_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always  # always ensures your container auto-restarts if EC2 reboots.
    volumes:
      - static_data:/app/staticfiles  # static_data stores collected static files
      - media_data:/app/media   # media_data stores uploaded media files when S3 is not used

volumes:
  static_data:
  media_data: